/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicVerifyMailSentRouteImport } from './routes/_public/verify-mail-sent'
import { Route as PublicVerifyMailRouteImport } from './routes/_public/verify-mail'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedGatewayRouteImport } from './routes/_authenticated/_gateway'
import { Route as AuthenticatedProfileProfileIdRouteImport } from './routes/_authenticated/profile.$profileId'
import { Route as AuthenticatedGatewayProfilesSelectionRouteImport } from './routes/_authenticated/_gateway/profiles-selection'
import { Route as AuthenticatedGatewayCreateProfileRouteImport } from './routes/_authenticated/_gateway/create-profile'
import { Route as AuthenticatedProfileProfileIdIndexRouteImport } from './routes/_authenticated/profile.$profileId/index'
import { Route as AuthenticatedProfileProfileIdMessagesRouteImport } from './routes/_authenticated/profile.$profileId/messages'
import { Route as AuthenticatedProfileProfileIdFriendsRouteImport } from './routes/_authenticated/profile.$profileId/friends'
import { Route as AuthenticatedProfileProfileIdFeedRouteImport } from './routes/_authenticated/profile.$profileId/feed'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyMailSentRoute = PublicVerifyMailSentRouteImport.update({
  id: '/verify-mail-sent',
  path: '/verify-mail-sent',
  getParentRoute: () => PublicRoute,
} as any)
const PublicVerifyMailRoute = PublicVerifyMailRouteImport.update({
  id: '/verify-mail',
  path: '/verify-mail',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedGatewayRoute = AuthenticatedGatewayRouteImport.update({
  id: '/_gateway',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileProfileIdRoute =
  AuthenticatedProfileProfileIdRouteImport.update({
    id: '/profile/$profileId',
    path: '/profile/$profileId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGatewayProfilesSelectionRoute =
  AuthenticatedGatewayProfilesSelectionRouteImport.update({
    id: '/profiles-selection',
    path: '/profiles-selection',
    getParentRoute: () => AuthenticatedGatewayRoute,
  } as any)
const AuthenticatedGatewayCreateProfileRoute =
  AuthenticatedGatewayCreateProfileRouteImport.update({
    id: '/create-profile',
    path: '/create-profile',
    getParentRoute: () => AuthenticatedGatewayRoute,
  } as any)
const AuthenticatedProfileProfileIdIndexRoute =
  AuthenticatedProfileProfileIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileProfileIdRoute,
  } as any)
const AuthenticatedProfileProfileIdMessagesRoute =
  AuthenticatedProfileProfileIdMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedProfileProfileIdRoute,
  } as any)
const AuthenticatedProfileProfileIdFriendsRoute =
  AuthenticatedProfileProfileIdFriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => AuthenticatedProfileProfileIdRoute,
  } as any)
const AuthenticatedProfileProfileIdFeedRoute =
  AuthenticatedProfileProfileIdFeedRouteImport.update({
    id: '/feed',
    path: '/feed',
    getParentRoute: () => AuthenticatedProfileProfileIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/verify-mail': typeof PublicVerifyMailRoute
  '/verify-mail-sent': typeof PublicVerifyMailSentRoute
  '/create-profile': typeof AuthenticatedGatewayCreateProfileRoute
  '/profiles-selection': typeof AuthenticatedGatewayProfilesSelectionRoute
  '/profile/$profileId': typeof AuthenticatedProfileProfileIdRouteWithChildren
  '/profile/$profileId/feed': typeof AuthenticatedProfileProfileIdFeedRoute
  '/profile/$profileId/friends': typeof AuthenticatedProfileProfileIdFriendsRoute
  '/profile/$profileId/messages': typeof AuthenticatedProfileProfileIdMessagesRoute
  '/profile/$profileId/': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/verify-mail': typeof PublicVerifyMailRoute
  '/verify-mail-sent': typeof PublicVerifyMailSentRoute
  '/create-profile': typeof AuthenticatedGatewayCreateProfileRoute
  '/profiles-selection': typeof AuthenticatedGatewayProfilesSelectionRoute
  '/profile/$profileId/feed': typeof AuthenticatedProfileProfileIdFeedRoute
  '/profile/$profileId/friends': typeof AuthenticatedProfileProfileIdFriendsRoute
  '/profile/$profileId/messages': typeof AuthenticatedProfileProfileIdMessagesRoute
  '/profile/$profileId': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/_gateway': typeof AuthenticatedGatewayRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/verify-mail': typeof PublicVerifyMailRoute
  '/_public/verify-mail-sent': typeof PublicVerifyMailSentRoute
  '/_authenticated/_gateway/create-profile': typeof AuthenticatedGatewayCreateProfileRoute
  '/_authenticated/_gateway/profiles-selection': typeof AuthenticatedGatewayProfilesSelectionRoute
  '/_authenticated/profile/$profileId': typeof AuthenticatedProfileProfileIdRouteWithChildren
  '/_authenticated/profile/$profileId/feed': typeof AuthenticatedProfileProfileIdFeedRoute
  '/_authenticated/profile/$profileId/friends': typeof AuthenticatedProfileProfileIdFriendsRoute
  '/_authenticated/profile/$profileId/messages': typeof AuthenticatedProfileProfileIdMessagesRoute
  '/_authenticated/profile/$profileId/': typeof AuthenticatedProfileProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/verify-mail'
    | '/verify-mail-sent'
    | '/create-profile'
    | '/profiles-selection'
    | '/profile/$profileId'
    | '/profile/$profileId/feed'
    | '/profile/$profileId/friends'
    | '/profile/$profileId/messages'
    | '/profile/$profileId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/verify-mail'
    | '/verify-mail-sent'
    | '/create-profile'
    | '/profiles-selection'
    | '/profile/$profileId/feed'
    | '/profile/$profileId/friends'
    | '/profile/$profileId/messages'
    | '/profile/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/_gateway'
    | '/_public/login'
    | '/_public/register'
    | '/_public/verify-mail'
    | '/_public/verify-mail-sent'
    | '/_authenticated/_gateway/create-profile'
    | '/_authenticated/_gateway/profiles-selection'
    | '/_authenticated/profile/$profileId'
    | '/_authenticated/profile/$profileId/feed'
    | '/_authenticated/profile/$profileId/friends'
    | '/_authenticated/profile/$profileId/messages'
    | '/_authenticated/profile/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-mail-sent': {
      id: '/_public/verify-mail-sent'
      path: '/verify-mail-sent'
      fullPath: '/verify-mail-sent'
      preLoaderRoute: typeof PublicVerifyMailSentRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/verify-mail': {
      id: '/_public/verify-mail'
      path: '/verify-mail'
      fullPath: '/verify-mail'
      preLoaderRoute: typeof PublicVerifyMailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/_gateway': {
      id: '/_authenticated/_gateway'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedGatewayRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/$profileId': {
      id: '/_authenticated/profile/$profileId'
      path: '/profile/$profileId'
      fullPath: '/profile/$profileId'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_gateway/profiles-selection': {
      id: '/_authenticated/_gateway/profiles-selection'
      path: '/profiles-selection'
      fullPath: '/profiles-selection'
      preLoaderRoute: typeof AuthenticatedGatewayProfilesSelectionRouteImport
      parentRoute: typeof AuthenticatedGatewayRoute
    }
    '/_authenticated/_gateway/create-profile': {
      id: '/_authenticated/_gateway/create-profile'
      path: '/create-profile'
      fullPath: '/create-profile'
      preLoaderRoute: typeof AuthenticatedGatewayCreateProfileRouteImport
      parentRoute: typeof AuthenticatedGatewayRoute
    }
    '/_authenticated/profile/$profileId/': {
      id: '/_authenticated/profile/$profileId/'
      path: '/'
      fullPath: '/profile/$profileId/'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedProfileProfileIdRoute
    }
    '/_authenticated/profile/$profileId/messages': {
      id: '/_authenticated/profile/$profileId/messages'
      path: '/messages'
      fullPath: '/profile/$profileId/messages'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdMessagesRouteImport
      parentRoute: typeof AuthenticatedProfileProfileIdRoute
    }
    '/_authenticated/profile/$profileId/friends': {
      id: '/_authenticated/profile/$profileId/friends'
      path: '/friends'
      fullPath: '/profile/$profileId/friends'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdFriendsRouteImport
      parentRoute: typeof AuthenticatedProfileProfileIdRoute
    }
    '/_authenticated/profile/$profileId/feed': {
      id: '/_authenticated/profile/$profileId/feed'
      path: '/feed'
      fullPath: '/profile/$profileId/feed'
      preLoaderRoute: typeof AuthenticatedProfileProfileIdFeedRouteImport
      parentRoute: typeof AuthenticatedProfileProfileIdRoute
    }
  }
}

interface AuthenticatedGatewayRouteChildren {
  AuthenticatedGatewayCreateProfileRoute: typeof AuthenticatedGatewayCreateProfileRoute
  AuthenticatedGatewayProfilesSelectionRoute: typeof AuthenticatedGatewayProfilesSelectionRoute
}

const AuthenticatedGatewayRouteChildren: AuthenticatedGatewayRouteChildren = {
  AuthenticatedGatewayCreateProfileRoute:
    AuthenticatedGatewayCreateProfileRoute,
  AuthenticatedGatewayProfilesSelectionRoute:
    AuthenticatedGatewayProfilesSelectionRoute,
}

const AuthenticatedGatewayRouteWithChildren =
  AuthenticatedGatewayRoute._addFileChildren(AuthenticatedGatewayRouteChildren)

interface AuthenticatedProfileProfileIdRouteChildren {
  AuthenticatedProfileProfileIdFeedRoute: typeof AuthenticatedProfileProfileIdFeedRoute
  AuthenticatedProfileProfileIdFriendsRoute: typeof AuthenticatedProfileProfileIdFriendsRoute
  AuthenticatedProfileProfileIdMessagesRoute: typeof AuthenticatedProfileProfileIdMessagesRoute
  AuthenticatedProfileProfileIdIndexRoute: typeof AuthenticatedProfileProfileIdIndexRoute
}

const AuthenticatedProfileProfileIdRouteChildren: AuthenticatedProfileProfileIdRouteChildren =
  {
    AuthenticatedProfileProfileIdFeedRoute:
      AuthenticatedProfileProfileIdFeedRoute,
    AuthenticatedProfileProfileIdFriendsRoute:
      AuthenticatedProfileProfileIdFriendsRoute,
    AuthenticatedProfileProfileIdMessagesRoute:
      AuthenticatedProfileProfileIdMessagesRoute,
    AuthenticatedProfileProfileIdIndexRoute:
      AuthenticatedProfileProfileIdIndexRoute,
  }

const AuthenticatedProfileProfileIdRouteWithChildren =
  AuthenticatedProfileProfileIdRoute._addFileChildren(
    AuthenticatedProfileProfileIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedGatewayRoute: typeof AuthenticatedGatewayRouteWithChildren
  AuthenticatedProfileProfileIdRoute: typeof AuthenticatedProfileProfileIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedGatewayRoute: AuthenticatedGatewayRouteWithChildren,
  AuthenticatedProfileProfileIdRoute:
    AuthenticatedProfileProfileIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicVerifyMailRoute: typeof PublicVerifyMailRoute
  PublicVerifyMailSentRoute: typeof PublicVerifyMailSentRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicVerifyMailRoute: PublicVerifyMailRoute,
  PublicVerifyMailSentRoute: PublicVerifyMailSentRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
